name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: say-hello
        run: echo "Hello there"
      - name: say-bye
        run: echo "Bye Bye"
